name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Jekyll site as artifact (for deploy job)
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: ./_site

      - name: Install Node.js using NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 14
          nvm use 14
        shell: bash

      - name: Install dependencies with Yarn
        run: yarn
        working-directory: ./

      - name: Build project with Yarn
        run: |
          git config --global user.name 'Furqan Sayyed'
          git config --global user.email 'furqansa344@gmail.com'
          export NODE_OPTIONS=--openssl-legacy-provider
          npx browserslist@latest --update-db
          yarn run build
        working-directory: ./

      - name: Deploy with Yarn
        run: yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
